default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: itsgifnotjif_development

test:
  <<: *default
  database: itsgifnotjif_test

production:
  <<: *default
  database: itsgifnotjif_production
  username: gschool_user
  password: <%= ENV['ITSGIFNOTJIF_DATABASE_PASSWORD'] %>